### ISSUE TITLE
Support larger file sizes

### ISSUE THREAD

**Issue by zeitchef** [loganmarchione/docker-webdav-nginx#16]
I'm getting some 413 errors `Request entity too large` when syncing some data - would you consider setting `client_max_body_size` in the nginx configuration to support larger file sizes?

**Comment by loganmarchione** [comment]
@zeitchef yep I can do that. What values were you thinking?

I could also probably make it an env var so that you can set it yourself.

**Comment by zeitchef** [comment]
I think an environment variable is the way to go, disabling it completely may not be expected behavior or what people want per default.

**Comment by loganmarchione** [comment]
@zeitchef Please test this tag. You'll have to add the variable `NGINX_CLIENT_MAX_BODY_SIZE` (be sure to include the units). Example docker-compose was updated [here](https://github.com/loganmarchione/docker-webdav-nginx#example-usage).
